services:
    hytale:
        image: ghcr.io/termermc/hytale-server:latest
        build:
            context: .
            dockerfile: ./Dockerfile

        tty: true
        stdin_open: true

        volumes:
         - ./runtime:/data/hytale/runtime

        ports:
         - 5520:5520/udp
